name       : ruby-ed25519
version    : 1.2.4
release    : 1
source     :
    - https://rubygems.org/downloads/ed25519-1.2.4.gem : dc62c3491e9484d566519ab2bfca1406c7527694c902e6d05074c3a33ecab3b8
license    : MIT
component  : programming.ruby
summary    : RubyGem - ed25519
description: |
    A Ruby binding to the Ed25519 elliptic curve public-key signature system described in RFC 8032.
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - ruby
install    : |
    %gem_install
